### ISSUE TITLE
Unable to establish an API connection on MacOS.

### ISSUE THREAD

**Issue by lkhphuc** [SoftCreatR/warp-up#1]
Hi, thanks for the education program. 
I know Mac is not supported but just want to report that here.

**Attach the following commands output**

- [x] lsb_release -a : 
`sysctl kern.version
kern.version: Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64`

**Describe the bug**
Terminal output:
```
 ##################
 Generation Process
 ##################

tr: Illegal byte sequence        [..]
tr: Illegal byte sequence
tr: Illegal byte sequence
```

warp-up.log
```
Warp-Up Version   : 
Warp ID           : xxxxxx
Iterations        : 3
Interval          : 20

Process Start     : Mon 30 Nov 2020 17:43:20 GMT

======

\ec
[1;31mUnable to establish an API connection. Aborting.[0m

```

**Comment by SoftCreatR** [comment]
Thank you for your report. Maybe, the Api has changed over time. I'll check that.

**Comment by SoftCreatR** [comment]
What I can tell is, that it still works under Linux and Windows. It's hard for me to reproduce without a Mac ;)
